# Generated by Codex on 2026-02-23

from django.db import migrations, models


def seed_products(apps, schema_editor):
    Product = apps.get_model("core", "Product")
    catalog = [
        {
            "name": "Spring Fresh Bottle",
            "volume_label": "250ml",
            "price": "15.00",
            "stock_quantity": 150,
            "is_featured": True,
            "description": "Compact hydration bottle for travel and meetings.",
            "image_url": "https://images.unsplash.com/photo-1564419320461-6870880221ad?auto=format&fit=crop&w=900&q=80",
        },
        {
            "name": "Daily Hydrate Bottle",
            "volume_label": "500ml",
            "price": "25.00",
            "stock_quantity": 200,
            "is_featured": True,
            "description": "Everyday bottle for school, commute, and quick hydration.",
            "image_url": "https://images.unsplash.com/photo-1560847468-5eef330f6f60?auto=format&fit=crop&w=900&q=80",
        },
        {
            "name": "Family Water Bottle",
            "volume_label": "1L",
            "price": "40.00",
            "stock_quantity": 130,
            "is_featured": True,
            "description": "Balanced size for home dining and office desks.",
            "image_url": "https://images.unsplash.com/photo-1548839140-29a749e1cf4d?auto=format&fit=crop&w=900&q=80",
        },
        {
            "name": "Active Life Bottle",
            "volume_label": "2L",
            "price": "70.00",
            "stock_quantity": 85,
            "is_featured": True,
            "description": "Large bottle for workout routines and long shifts.",
            "image_url": "https://images.unsplash.com/photo-1523362628745-0c100150b504?auto=format&fit=crop&w=900&q=80",
        },
        {
            "name": "Home Reserve Can",
            "volume_label": "5L",
            "price": "150.00",
            "stock_quantity": 60,
            "is_featured": True,
            "description": "Best for family storage and kitchen refill use.",
            "image_url": "https://images.unsplash.com/photo-1543393470-b2c6d2d8aa7b?auto=format&fit=crop&w=900&q=80",
        },
        {
            "name": "Office Bulk Can",
            "volume_label": "20L",
            "price": "320.00",
            "stock_quantity": 45,
            "is_featured": True,
            "description": "Bulk can suited for office pantry dispensers.",
            "image_url": "https://images.unsplash.com/photo-1561047029-3000c68339ca?auto=format&fit=crop&w=900&q=80",
        },
        {
            "name": "Party Pack",
            "volume_label": "12 x 500ml",
            "price": "270.00",
            "stock_quantity": 90,
            "is_featured": False,
            "description": "Bundle of twelve 500ml bottles for events and gatherings.",
            "image_url": "https://images.unsplash.com/photo-1550505095-81378a674395?auto=format&fit=crop&w=900&q=80",
        },
        {
            "name": "Value Pack",
            "volume_label": "6 x 1L",
            "price": "220.00",
            "stock_quantity": 100,
            "is_featured": False,
            "description": "Six-pack of 1L bottles for weekly household use.",
            "image_url": "https://images.unsplash.com/photo-1616117446860-4f588de53d74?auto=format&fit=crop&w=900&q=80",
        },
    ]

    for item in catalog:
        Product.objects.update_or_create(
            name=item["name"],
            volume_label=item["volume_label"],
            defaults=item,
        )


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_featured",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="product",
            name="stock_quantity",
            field=models.PositiveIntegerField(default=50),
        ),
        migrations.AddField(
            model_name="product",
            name="volume_label",
            field=models.CharField(default="1L", max_length=50),
        ),
        migrations.RunPython(seed_products, migrations.RunPython.noop),
    ]
