# Generated by Codex on 2026-02-23

from django.db import migrations


def refresh_catalog(apps, schema_editor):
    Product = apps.get_model("core", "Product")

    Product.objects.all().delete()

    catalog = [
        {
            "name": "HydroHub Aqua Mini",
            "volume_label": "250ml",
            "price": "15.00",
            "stock_quantity": 300,
            "is_featured": True,
            "description": "Single-serve bottle for meetings, classrooms, and travel bags.",
            "image_url": "https://dummyimage.com/900x650/0b6ef6/ffffff.png?text=HydroHub+Logo+250ml+Bottle",
        },
        {
            "name": "HydroHub Fresh Sip",
            "volume_label": "300ml",
            "price": "18.00",
            "stock_quantity": 260,
            "is_featured": True,
            "description": "Lightweight compact bottle with clear HydroHub label.",
            "image_url": "https://dummyimage.com/900x650/08b7d7/ffffff.png?text=HydroHub+Logo+300ml+Bottle",
        },
        {
            "name": "HydroHub Daily Bottle",
            "volume_label": "500ml",
            "price": "25.00",
            "stock_quantity": 240,
            "is_featured": True,
            "description": "Popular everyday hydration bottle for personal use.",
            "image_url": "https://dummyimage.com/900x650/0f1d40/ffffff.png?text=HydroHub+Logo+500ml+Bottle",
        },
        {
            "name": "HydroHub Sport Cap",
            "volume_label": "750ml",
            "price": "34.00",
            "stock_quantity": 180,
            "is_featured": True,
            "description": "Mid-size bottle for sports and gym hydration.",
            "image_url": "https://dummyimage.com/900x650/1d77ff/ffffff.png?text=HydroHub+Logo+750ml+Bottle",
        },
        {
            "name": "HydroHub Family Bottle",
            "volume_label": "1L",
            "price": "42.00",
            "stock_quantity": 210,
            "is_featured": True,
            "description": "Classic one-litre bottle for home and office desks.",
            "image_url": "https://dummyimage.com/900x650/00a9c8/ffffff.png?text=HydroHub+Logo+1L+Bottle",
        },
        {
            "name": "HydroHub Double Bottle",
            "volume_label": "2L",
            "price": "72.00",
            "stock_quantity": 160,
            "is_featured": True,
            "description": "Two-litre bottle with long-use drinking capacity.",
            "image_url": "https://dummyimage.com/900x650/1660d6/ffffff.png?text=HydroHub+Logo+2L+Bottle",
        },
        {
            "name": "HydroHub Kitchen Can",
            "volume_label": "3L",
            "price": "110.00",
            "stock_quantity": 110,
            "is_featured": False,
            "description": "Kitchen-ready can for cooking and day-long consumption.",
            "image_url": "https://dummyimage.com/900x650/0b6ef6/ffffff.png?text=HydroHub+Logo+3L+Can",
        },
        {
            "name": "HydroHub Home Can",
            "volume_label": "5L",
            "price": "155.00",
            "stock_quantity": 100,
            "is_featured": False,
            "description": "Five-litre can designed for family refill usage.",
            "image_url": "https://dummyimage.com/900x650/08b7d7/ffffff.png?text=HydroHub+Logo+5L+Can",
        },
        {
            "name": "HydroHub Office Can",
            "volume_label": "10L",
            "price": "230.00",
            "stock_quantity": 80,
            "is_featured": False,
            "description": "Ten-litre can for offices and small workspaces.",
            "image_url": "https://dummyimage.com/900x650/0f1d40/ffffff.png?text=HydroHub+Logo+10L+Can",
        },
        {
            "name": "HydroHub Dispenser Jar",
            "volume_label": "20L",
            "price": "330.00",
            "stock_quantity": 70,
            "is_featured": True,
            "description": "Large dispenser jar for pantry and reception areas.",
            "image_url": "https://dummyimage.com/900x650/1d77ff/ffffff.png?text=HydroHub+Logo+20L+Jar",
        },
        {
            "name": "HydroHub Event Pack",
            "volume_label": "12 x 250ml",
            "price": "165.00",
            "stock_quantity": 160,
            "is_featured": False,
            "description": "Twelve mini bottles for events and training sessions.",
            "image_url": "https://dummyimage.com/900x650/00a9c8/ffffff.png?text=HydroHub+Logo+12x250ml+Pack",
        },
        {
            "name": "HydroHub Party Pack",
            "volume_label": "12 x 500ml",
            "price": "285.00",
            "stock_quantity": 140,
            "is_featured": False,
            "description": "Twelve 500ml bottles for celebrations and gatherings.",
            "image_url": "https://dummyimage.com/900x650/1660d6/ffffff.png?text=HydroHub+Logo+12x500ml+Pack",
        },
        {
            "name": "HydroHub Value Crate",
            "volume_label": "24 x 500ml",
            "price": "540.00",
            "stock_quantity": 95,
            "is_featured": False,
            "description": "Crate bundle for canteens, hostels, and events.",
            "image_url": "https://dummyimage.com/900x650/0b6ef6/ffffff.png?text=HydroHub+Logo+24x500ml+Crate",
        },
        {
            "name": "HydroHub Family Pack",
            "volume_label": "6 x 1L",
            "price": "230.00",
            "stock_quantity": 130,
            "is_featured": False,
            "description": "Six one-litre bottles for weekly household planning.",
            "image_url": "https://dummyimage.com/900x650/08b7d7/ffffff.png?text=HydroHub+Logo+6x1L+Pack",
        },
        {
            "name": "HydroHub Mega Pack",
            "volume_label": "12 x 1L",
            "price": "450.00",
            "stock_quantity": 100,
            "is_featured": False,
            "description": "Bulk one-litre case for office teams and schools.",
            "image_url": "https://dummyimage.com/900x650/0f1d40/ffffff.png?text=HydroHub+Logo+12x1L+Pack",
        },
        {
            "name": "HydroHub Office Duo",
            "volume_label": "2 x 20L",
            "price": "640.00",
            "stock_quantity": 65,
            "is_featured": False,
            "description": "Dual 20-litre jar combo for continuous office supply.",
            "image_url": "https://dummyimage.com/900x650/1d77ff/ffffff.png?text=HydroHub+Logo+2x20L+Combo",
        },
    ]

    Product.objects.bulk_create([Product(**item) for item in catalog])


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_product_catalog_upgrade"),
    ]

    operations = [
        migrations.RunPython(refresh_catalog, migrations.RunPython.noop),
    ]
