# Generated by Codex on 2026-02-23

from django.db import migrations, models


def assign_local_images(apps, schema_editor):
    Product = apps.get_model("core", "Product")

    for product in Product.objects.all():
        label = (product.volume_label or "").lower()

        if "x" in label:
            image = "/static/core/products/pack.svg"
        elif "20l" in label:
            image = "/static/core/products/jar-20l.svg"
        elif any(size in label for size in ["3l", "5l", "10l"]):
            image = "/static/core/products/can-3to10l.svg"
        elif any(size in label for size in ["250ml", "300ml", "500ml"]):
            image = "/static/core/products/bottle-small.svg"
        elif any(size in label for size in ["750ml", "1l", "2l"]):
            image = "/static/core/products/bottle-medium.svg"
        else:
            image = "/static/core/products/default-bottle.svg"

        product.image_url = image
        product.save(update_fields=["image_url"])


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_refresh_catalog_with_branded_images"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image_url",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.RunPython(assign_local_images, migrations.RunPython.noop),
    ]
