# Generated by Codex on 2026-02-23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_local_product_images"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="current_location",
            field=models.CharField(default="HydroHub Warehouse", max_length=120),
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_address",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_city",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_name",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_phone",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_pincode",
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AddField(
            model_name="order",
            name="tracking_latitude",
            field=models.DecimalField(decimal_places=6, default=12.9716, max_digits=9),
        ),
        migrations.AddField(
            model_name="order",
            name="tracking_longitude",
            field=models.DecimalField(decimal_places=6, default=77.5946, max_digits=9),
        ),
        migrations.AddField(
            model_name="order",
            name="tracking_status",
            field=models.CharField(default="Order Confirmed", max_length=40),
        ),
    ]
