# Generated by Codex on 2026-02-23

from django.db import migrations, models


def rename_brand_data(apps, schema_editor):
    Product = apps.get_model("core", "Product")
    Order = apps.get_model("core", "Order")

    for product in Product.objects.filter(name__startswith="HydroHub"):
        product.name = product.name.replace("HydroHub", "WaterSupply", 1)
        product.description = (product.description or "").replace("HydroHub", "WaterSupply")
        product.save(update_fields=["name", "description"])

    for order in Order.objects.filter(current_location__contains="HydroHub"):
        order.current_location = order.current_location.replace("HydroHub", "WaterSupply")
        order.save(update_fields=["current_location"])


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_order_address_and_tracking"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="current_location",
            field=models.CharField(default="WaterSupply Warehouse", max_length=120),
        ),
        migrations.RunPython(rename_brand_data, migrations.RunPython.noop),
    ]
