# Generated by Codex on 2026-02-23

from django.db import migrations


def assign_original_images(apps, schema_editor):
    Product = apps.get_model("core", "Product")

    for product in Product.objects.all():
        label = (product.volume_label or "").lower()

        if "x" in label:
            image = "/static/core/products/original-pack.svg"
        elif "20l" in label:
            image = "/static/core/products/original-jar.svg"
        elif any(size in label for size in ["3l", "5l", "10l"]):
            image = "/static/core/products/original-can.svg"
        elif "250ml" in label:
            image = "/static/core/products/original-mini.svg"
        elif "500ml" in label:
            image = "/static/core/products/original-daily.svg"
        elif "750ml" in label:
            image = "/static/core/products/original-sport.svg"
        elif "1l" in label:
            image = "/static/core/products/original-family.svg"
        elif "2l" in label:
            image = "/static/core/products/original-double.svg"
        else:
            image = "/static/core/products/original-default.svg"

        product.image_url = image
        product.save(update_fields=["image_url"])


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_rename_brand_to_watersupply"),
    ]

    operations = [
        migrations.RunPython(assign_original_images, migrations.RunPython.noop),
    ]
