# Generated by Codex on 2026-02-23

from django.db import migrations


def fix_300ml_mapping(apps, schema_editor):
    Product = apps.get_model("core", "Product")
    Product.objects.filter(volume_label__iexact="300ml").update(
        image_url="/static/core/products/original-mini.svg"
    )


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_assign_original_bottle_images"),
    ]

    operations = [
        migrations.RunPython(fix_300ml_mapping, migrations.RunPython.noop),
    ]
