# Generated by Codex on 2026-02-23

from django.db import migrations


def force_fix_300ml_mapping(apps, schema_editor):
    Product = apps.get_model("core", "Product")
    for product in Product.objects.all():
        if "300ml" in (product.volume_label or "").lower():
            product.image_url = "/static/core/products/original-mini.svg"
            product.save(update_fields=["image_url"])


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_fix_300ml_image_mapping"),
    ]

    operations = [
        migrations.RunPython(force_fix_300ml_mapping, migrations.RunPython.noop),
    ]
