# Generated by Django 6.0.2 on 2026-03-01 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_category_coupon_alter_product_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="fulfillment_type",
            field=models.CharField(
                choices=[
                    ("one_time", "One-time"),
                    ("weekly", "Weekly Subscription"),
                    ("monthly", "Monthly Subscription"),
                ],
                default="one_time",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("frequency", models.CharField(choices=[("weekly", "Weekly"), ("monthly", "Monthly")], max_length=20)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("paused", "Paused"), ("cancelled", "Cancelled")],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("start_date", models.DateField()),
                ("next_delivery_date", models.DateField()),
                ("delivery_name", models.CharField(max_length=120)),
                ("delivery_phone", models.CharField(max_length=20)),
                ("delivery_address", models.CharField(max_length=255)),
                ("delivery_city", models.CharField(max_length=100)),
                ("delivery_pincode", models.CharField(max_length=12)),
                (
                    "payment_method",
                    models.CharField(
                        choices=[("cod", "Cash on Delivery"), ("razorpay", "Razorpay"), ("stripe", "Stripe")],
                        default="cod",
                        max_length=20,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscriptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "last_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="source_subscriptions",
                        to="core.order",
                    ),
                ),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="SubscriptionItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "product",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="core.product"),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="core.subscription",
                    ),
                ),
            ],
        ),
    ]
