# Generated by Codex on 2026-03-01

from django.db import migrations


def assign_photo_urls(apps, schema_editor):
    Product = apps.get_model("core", "Product")

    for product in Product.objects.all():
        name = (product.name or "").lower()
        label = (product.volume_label or "").lower()

        if "20l" in label or "jar" in name:
            image = "https://source.unsplash.com/1200x1200/?water,dispenser"
        elif any(size in label for size in ["3l", "5l", "10l"]) or "can" in name:
            image = "https://source.unsplash.com/1200x1200/?water,canister"
        elif "pack" in name or "x" in label:
            image = "https://source.unsplash.com/1200x1200/?water,bottle,pack"
        elif any(size in label for size in ["250ml", "300ml", "500ml"]):
            image = "https://source.unsplash.com/1200x1200/?small,water,bottle"
        else:
            image = "https://source.unsplash.com/1200x1200/?mineral-water,bottle"

        product.image_url = image
        product.save(update_fields=["image_url"])


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0011_order_fulfillment_type_subscription_and_more"),
    ]

    operations = [
        migrations.RunPython(assign_photo_urls, migrations.RunPython.noop),
    ]
