# Generated by Codex on 2026-03-01

from django.db import migrations


def assign_local_photo_images(apps, schema_editor):
    Product = apps.get_model("core", "Product")

    for product in Product.objects.all():
        name = (product.name or "").lower()
        label = (product.volume_label or "").lower()

        if "20l" in label or "jar" in name or "dispenser" in name:
            image = "/static/core/products/photos/jar-photo.png"
        elif any(size in label for size in ["3l", "5l", "10l"]) or "can" in name:
            image = "/static/core/products/photos/can-photo.png"
        elif "pack" in name or "x" in label:
            image = "/static/core/products/photos/pack-photo.png"
        elif any(size in label for size in ["250ml", "300ml", "500ml"]):
            image = "/static/core/products/photos/bottle-small-photo.png"
        elif any(size in label for size in ["750ml", "1l", "2l"]):
            image = "/static/core/products/photos/bottle-medium-photo.png"
        else:
            image = "/static/core/products/photos/bottle-large-photo.png"

        product.image_url = image
        product.save(update_fields=["image_url"])


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0012_assign_photo_image_urls"),
    ]

    operations = [
        migrations.RunPython(assign_local_photo_images, migrations.RunPython.noop),
    ]
